#!/bin/bash
# Install DSGVO check as Git pre-commit hook
# Version: 1.00

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${YELLOW}Installing DSGVO pre-commit hook...${NC}"

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo -e "${RED}❌ Error: Not a git repository${NC}"
    echo "   Run this from the project root directory"
    exit 1
fi

# Check if hook script exists
HOOK_SCRIPT="tools/dsgvo-check/check-customer-data.sh"
if [ ! -f "$HOOK_SCRIPT" ]; then
    echo -e "${RED}❌ Error: $HOOK_SCRIPT not found${NC}"
    echo "   Make sure tools/dsgvo-check/ is present in your project"
    exit 1
fi

# Create hooks directory if missing
mkdir -p .git/hooks

# Install hook
HOOK_PATH=".git/hooks/pre-commit"

# Backup existing hook if present
if [ -f "$HOOK_PATH" ]; then
    echo -e "${YELLOW}⚠️  Existing pre-commit hook found${NC}"
    echo "   Backing up to: ${HOOK_PATH}.backup"
    cp "$HOOK_PATH" "${HOOK_PATH}.backup"
fi

# Create the hook
cat > "$HOOK_PATH" << 'EOF'
#!/bin/bash
# Git pre-commit hook - DSGVO customer data check
# Auto-generated by install-pre-commit-hook.sh

# Run DSGVO check
bash tools/dsgvo-check/check-customer-data.sh

# Pass exit code from check script
exit $?
EOF

# Make hook executable
chmod +x "$HOOK_PATH"

echo -e "${GREEN}✅ DSGVO pre-commit hook installed${NC}"
echo ""
echo "Next steps:"
echo "  1. (Optional) Copy .dsgvo-check.conf.example to .dsgvo-check.conf"
echo "  2. (Optional) Configure customer domains/names in .dsgvo-check.conf"
echo "  3. Test: Stage some files and try to commit"
echo ""
echo "The hook will now run automatically before every commit."
echo "To skip the hook (not recommended): git commit --no-verify"
